{{- range .Values.persistentVolume }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  capacity:
    storage: {{ .size }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .hostPath }}
---
{{- end }}
